title: Suyash
email: dextrous93@gmail.com
description: Suyash's Website
url: "https://suy.io"
twitter_username: dextrous93
medium_username: suyash93
github_username: suyash
kaggle_username: suyash93
stackoverflow_id: 3673043
gaid: UA-80985362-2

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose*
