title: Suyash
email: dextrous93@gmail.com
description: Suyash's Website
url: "https://suyash.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dextrous93
medium_username: suyash93
linkedin_username: suyash93
github_username:  suyash
gaid: UA-80985362-1

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
