name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - run: yarn install

      - run: yarn build

      - name: switch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --no-recurse-submodules
          git switch gh-pages
          mv dist/* ./

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: push
        run: |
          if [[ -n $(git status -s -uall) ]];
          then
            git add --all
            git commit -m "build"
            git push
          else
            echo "No Changes to Push"
          fi
